import { FC, useContext, useState } from "react";
import OutlinedInput from '@material-ui/core/OutlinedInput';
import { Button as MaterialButton, InputAdornment } from "@material-ui/core";
import { Web3Context } from "../../contexts/Web3.context";
import Button from '../Button/Button';

const Stake: FC = () => {
  const [amount, setAmount] = useState(0);
  const [isApproved, setApproved] = useState(false);
  const handleChange = (event) => {
    console.log(event.target.value)
    setAmount(parseInt(event.target.value, 10));
  }
  const web3 = useContext(Web3Context)

  const getMaxNu = async () => {
    console.info('implement me');
    setAmount(10)
  }

  const approveContract = async () => {
    console.info('implement me')
  }

  const sendTx = async () => {

  }
  return (
    <>
      <article style={{ display: 'flex', justifyContent: 'space-between', padding: '36px' }}>
        <div>
          <h3>23</h3>
          <p>Staking Lots Purchased</p>
        </div>
        <div>
          <h3>12</h3>
          <p>Eth Lots</p>
        </div>
        <div>
          <h3>11</h3>
          <p>BTC Lots</p>
        </div>
        <div>
          <h3>21M</h3>
          <p>NU in pool</p>
        </div>
      </article>
      <article style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', margin: '80px', marginBottom: 'auto' }}>
        <OutlinedInput style={{ borderRadius: '15px', width: '100%' }} value={amount} onChange={handleChange} type="number"
          endAdornment={(
            <>
              <InputAdornment position="end" style={{ alignItems: 'initial' }} onClick={getMaxNu}>
                <MaterialButton><span style={{ fontStyle: 'italic', fontWeight: 600 }}>Max</span></MaterialButton>
              </InputAdornment>
              <InputAdornment position="end" style={{ alignItems: 'initial' }}>
                <MaterialButton><span style={{ fontStyle: 'italic', fontWeight: 600 }}>NU</span></MaterialButton>
              </InputAdornment>
            </>
          )} />
        <div style={{ margin: '24px', width: '100%', display: 'flex', justifyContent: 'space-between' }}>
          <Button onClick={approveContract} disabled={isApproved}>Approve</Button>
          <Button onClick={sendTx} disabled={!isApproved}>Deposit</Button>
        </div>
      </article>
      <p>
        Deposit your NU in the pool and start earning fees <br /> generated by the Hegic Protocol.
        <ul>
          <ol>
            <li>
              Deposit your NU
            </li>
            <li>
              You start earning ETH and WBTC right away.
            </li>
            <li>
              Yes, both ETH and WBTC.
            </li>
            <li>
              You can withdraw your NU anytime.
            </li>
          </ol>
        </ul>
      </p>
    </>
  )
}

export default Stake;